### ISSUE TITLE
StandardJS for Javascript code standards

### ISSUE THREAD

**Issue by riteshghorse** [ultraultimated/savitar#34]
@ultraultimated is it possible to use both [standardjs](https://standardjs.com/) and ESLint in the same project?

**Comment by ultraultimated** [comment]
ESLint and Standard JS belong to "Code Review" category of the tech stack. ESLint is an open source tool with 14.4K GitHub stars and 2.47K GitHub forks. ... Asana, Rainist, and Intuit are some of the popular companies that use ESLint, whereas Standard JS is used by NodeSource, commonality, and Stickermule. Since our project is mostly written in plain javascript I would keep eslint as our standard code checker.
